apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 250Mi  # Ensure this matches the PVC request
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data  # Change this to a suitable path for your environment
  storageClassName: default
