# apiVersion: v1
# kind: Service
# metadata:
#   name: site-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: site-deployment
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  type: NodePort
  selector:
    app: site-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30542  # Optional: You can specify a port or let Kubernetes assign one

