# Default values for ecommercesite-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

database:
  name: mariadb
  replicas: 1
  image:
    repository: mariadb
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  labels: 
    app: mariadb
  port: 3306

  service:
    name: mariadb-service
    type: ClusterIP
    port: 3306
  secret:
    name: mariadb-secret

  configmap:
    initsql:
      fullname: mariadb-initdb-config

  storage:
    persistentVolumeClaimName: mariadb-pvc


site:
  name: ecom-site
  replicas: 1
  image:
    repository: bishal2469/my_php_app
    pullPolicy: Always
    tag: "v3"
  port: 80
  labels:
    app: ecom-site
  
  service:
    name: site-service
    type: LoadBalancer
    port: 80
  
  secret:
    name: site-secret

  configmap:
    env:
      name: site-configmap
    featureToggle:
      name: feature-toggle-config


autoscaling:
  hpa:
    fullname: ecom-app-hpa
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 95
    targetMemoryUtilizationPercentage: 95
  

