name: Build and Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecom-web:latest

  deploy-to-eks:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Kubectl
        uses: aws-actions/setup-kubectl@v2
        with:
          version: '1.24.0'  # Specify the kubectl version as needed

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Set up Helm
        uses: helm/chart-releaser-action@v2

      - name: Helm Upgrade and Deploy
        run: helm upgrade --install ecommercesite ./ecommercesite-chart --set image.repository=${{ secrets.DOCKER_USERNAME }}/ecom-web,image.tag=latest
